platform :ios, '9.0'

target 'Runner' do
  use_frameworks!

  # Pods for YourAppTargetName
  pod 'PlayKitVRCustomized', :git => 'https://github.com/aldisa546/playkit-ios-vr.git'
  pod 'PlayKitProviders'

end
